project:
  name: quickstart-bmc-track-it
  owner: manish_gadgil@BMC.com
  package_lambda: true
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  s3_regional_buckets: true
  shorten_stack_name: true
  regions:
    - af-south-1      # Africa (Cape Town)
  # - ap-east-1       # Asia Pacific (Hong Kong)
  # - ap-northeast-1  # Asia Pacific (Tokyo)
  # - ap-northeast-2  # Asia Pacific (Seoul)
  # - ap-northeast-3  # Asia Pacific (Osaka)
  # - ap-south-1      # Asia Pacific (Mumbai)
  # - ap-southeast-1  # Asia Pacific (Singapore)
  # - ap-southeast-2  # Asia Pacific (Sydney)
    - ca-central-1    # Canada (Central)
    - eu-central-1    # Europe (Frankfurt)
    - eu-north-1      # Europe (Stockholm)
    - eu-south-1      # Europe (Milan)
    - eu-west-1       # Europe (Ireland)
    - eu-west-2       # Europe (London)
  # - eu-west-3       # Europe (Paris)
  # - me-south-1      # Middle East (Bahrain)
  # - sa-east-1       # South America (São Paulo)
    - us-east-1       # US East (N. Virginia)
    - us-east-2       # US East (Ohio)
    - us-west-1       # US West (N. California)
    - us-west-2       # US West (Oregon)
  parameters:
    AvailabilityZones: $[taskcat_genaz_2]
    DomainAdminPassword: $[taskcat_genpass_12A]
    DomainAdminPasswordConfirm: $[taskcat_getval_DomainAdminPassword]
    DomainDNSName: example.internal
    DomainNetBIOSName: example
    DSMicrosoftADEdition: Standard
    KeyPairName: $[taskcat_getkeypair]
    OperatorEmail: 'None'
    PrivateSubnet1ACIDR: 10.0.0.0/19
    PrivateSubnet2ACIDR: 10.0.32.0/19
    PublicSubnet1CIDR: 10.0.128.0/20
    PublicSubnet2CIDR: 10.0.144.0/20
    QSS3BucketName:  $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    QSS3KeyPrefix: quickstart-bmc-track-it/
    TrackItEndUserWebAccessCIDR: 0.0.0.0/0
    TrackItInstanceDomainComputerName: TrackIt01
    TrackItEnvironmentSize: Small (Up to 5 active technicians)
    VPCCIDR: 10.0.0.0/16
    TrackItAdminPassword: $[taskcat_getval_DomainAdminPassword]
    TrackItAdminPasswordConfirm: $[taskcat_getval_DomainAdminPassword]
    TrackItBcmAdminPassword: $[taskcat_getval_DomainAdminPassword]
    TrackItBcmAdminPasswordConfirm: $[taskcat_getval_DomainAdminPassword]
    
tests:
  # 'Small', Self-Signed Cert Configuration
  trackit-small-selfsign:
    regions:
      -  us-east-1
      -  us-east-2
    parameters:
      Route53HostedZoneId: ''
      TrackItSiteDomain: ''
      TrackItRealSSLCertificateARN: ''
      TrackItSelfSignSSLCertificateOptions: CN=trackit.org;C=US;L=Texas;ST=TX;O=trackit;OU=sales;E=customer_support@bmc.com
      TrackItSelfSignSSLCertificateExpiresOn: ''
    s3_bucket: ''
    template: ./templates/bmc-trackit-main.template.yaml

  
  # Uncomment the following to do local testing of the registered-domain use-case
  # To use, create a Route53 hosted zone for the registered domain name. Import an SSL
  # certificate into ACM or create an SSL cert in ACM and associate with the Route53
  # hosted zone, then provide values for the three parameters below
  
  # # 'Small', Registered domain name and certificate
  # trackit-small-registereddomain:
  #   parameters:
  #     Route53HostedZoneId: '**fill in**'
  #     TrackItSiteDomain: '**fill in**'
  #     TrackItRealSSLCertificateARN: '**fill in**'
  #     TrackItSelfSignSSLCertificateOptions: CN=trackit.org;C=US;L=Texas;ST=TX;O=trackit;OU=sales;E=customer_support@bmc.com
  #     TrackItSelfSignSSLCertificateExpiresOn: '2031-12-31'
  #   regions:
  #     -  us-east-2
  #   s3_bucket: ''
  #   template: ./templates/bmc-trackit-main.template.yaml

