project:
  name: quickstart-bmc-track-it
  owner: manish_gadgil@BMC.com
  package_lambda: false
  s3_regional_buckets: true
  shorten_stack_name: true
  regions:
    - us-east-1
  s3_bucket: ''
  parameters:
    AvailabilityZones: $[taskcat_genaz_2]
    KeyPairName: $[taskcat_getkeypair]
    OperatorEmail: 'None'
    PrivateSubnet1ACIDR: 10.0.0.0/19
    PrivateSubnet2ACIDR: 10.0.32.0/19
    PublicSubnet1CIDR: 10.0.128.0/20
    PublicSubnet2CIDR: 10.0.144.0/20
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    QSS3KeyPrefix: quickstart-bmc-track-it/
    Route53HostedZoneId: ''
    TrackItEndUserWebAccessCIDR: 0.0.0.0/0
    TrackItInstanceType: m5.large
    TrackItSiteDomain: ''
    TrackItSSLCertificateARN: ''
    VPCCIDR: 10.0.0.0/16

tests:
  # Single Server Configuration
  trackit-single-server:
    regions:
    - us-east-1
    s3_bucket: ''
    template: ./templates/bmc-trackit-master.template.yaml

  # # Seperate Client Management Server Configuration
  # trackit-separate-client-server:
  #   parameters:
  #     ClientMgmtServerEmbedded: false
  #   regions:
  #    - us-east-1          # US East (N. Virginia)
  #   s3_bucket: ''
  #   template: ./templates/bmc-trackit-master.template.yaml

