project:
  name: quickstart-bmc-track-it
  owner: manish_gadgil@BMC.com
  package_lambda: true
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  s3_regional_buckets: true
  shorten_stack_name: true
  regions:
    - us-east-1
  s3_bucket: ''
  parameters:
    AvailabilityZones: $[taskcat_genaz_2]
    DomainAdminPassword: $[taskcat_genpass_12A]
    DomainAdminPasswordConfirm: $[taskcat_getval_DomainAdminPassword]
    DomainDNSName: example.internal
    DomainNetBIOSName: example
    DSMicrosoftADEdition: Standard
    KeyPairName: $[taskcat_getkeypair]
    OperatorEmail: 'None'
    PrivateSubnet1ACIDR: 10.0.0.0/19
    PrivateSubnet2ACIDR: 10.0.32.0/19
    PublicSubnet1CIDR: 10.0.128.0/20
    PublicSubnet2CIDR: 10.0.144.0/20
    QSS3BucketName:  $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    QSS3KeyPrefix: quickstart-bmc-track-it/
    Route53HostedZoneId: ''
    TrackItEndUserWebAccessCIDR: 0.0.0.0/0
    TrackItInstanceDomainComputerName: TrackIt01
    TrackItEnvironmentSize: Small
    TrackItSiteDomain: ''
    TrackItRealSSLCertificateARN: ''
    TrackItSelfSignSSLCertificateOptions: CN=trackit.org;C=US;L=Texas;ST=TX;O=trackit;OU=sales;E=customer_support@bmc.com
    TrackItSelfSignSSLCertificateExpiresOn: '2031-12-31'
    VPCCIDR: 10.0.0.0/16
    
tests:
  # 'Small', Self-Signed Cert Configuration
  trackit-small-selfsign:
    regions:
      # - us-east-2       # US East (Ohio)
      - us-east-1       # US East (N. Virginia)
      # - us-west-1       # US West (N. California)
      # - us-west-2       # US West (Oregon)
      # - af-south-1      # Africa (Cape Town)
      # - ap-east-1       # Asia Pacific (Hong Kong)
      # - ap-south-1      # Asia Pacific (Mumbai)
      # - ap-northeast-3  # Asia Pacific (Osaka)
      # - ap-northeast-2  # Asia Pacific (Seoul)
      # - ap-southeast-1  # Asia Pacific (Singapore)
      # - ap-southeast-2  # Asia Pacific (Sydney)
      # - ap-northeast-1  # Asia Pacific (Tokyo)
      # - ca-central-1    # Canada (Central)
      # - eu-central-1    # Europe (Frankfurt)
      # - eu-west-1       # Europe (Ireland)
      # - eu-west-2       # Europe (London)
      # - eu-south-1      # Europe (Milan)
      # - eu-west-3       # Europe (Paris)
      # - eu-north-1      # Europe (Stockholm)
      # - me-south-1      # Middle East (Bahrain)
      # - sa-east-1       # South America (São Paulo)
    s3_bucket: ''
    template: ./templates/bmc-trackit-master.template.yaml


  
